### ISSUE TITLE
When connecting to a expired cloud account I get a cryptic message. The message could be more helpful. 

### ISSUE THREAD

**Issue by roberhofer** [realm/realm-studio#1039]
**Is your feature request related to a problem? Please describe.**
When connecting via Studio to my cloud account I get the following error message: 
![image](https://user-images.githubusercontent.com/39501158/49821407-34725b00-fd2f-11e8-95e3-be01d3c14247.png)

The message is a bit confusing. It turns out that the account expired. 

**Describe the solution you'd like**
I would like to see a hint in addition to the existing error message that helps me further, such as: 
- "Is your account still active?"

**Describe alternatives you've considered**
None. 

**Additional context**
This message might be generic for all ROS servers (not just cloud.realm.io).

**Comment by kraenhansen** [comment]
A user with a suspended clound account should never get the button to connect to their Realm Cloud instance, instead I've added this issue: https://github.com/realm/realm-studio/issues/1051

**Comment by kraenhansen** [comment]
I intend to have it be the solution .. it's already fetching the users cloud account (list of instances), and if suspended or not .. we're just not using the latter to display a proper notice yet.

Re-reasing your original description I'm uncertain if you're talking about a suspended cloud account (due to missing payment) or an expired JWT token (which would fix itself by logging out and in again)?

**Comment by roberhofer** [comment]
@kraenhansen : Thanks for the clarification. Makes sense. 
The error code was visible when connecting to a cloud account that has not been used in a while and did expire in the meantime. 
 
It's unclear to me whether this error code was specifically triggered due to expired JWT token or suspended account. In either case the message could be more user friendly to guide how to take action to resolve the issue.
