### ISSUE TITLE
[RealStudio for Mac] The JS stack trace alert in the first launch.

### ISSUE THREAD

**Issue by schurik77799** [realm/realm-studio#1053]
**Describe the bug**
The JS stack trace alert in the first launch.

**To Reproduce**
1. Download the RealmStudio for Mac from here
https://realm.io/products/realm-studio/#download-studio
2. Try to launch it.
3. Observe an error on the screenshot.

**Expected behavior**
I don't expect an error at all.

**Screenshots**
<img width="421" alt="screenshot 2018-12-20 at 23 03 18" src="https://user-images.githubusercontent.com/11133998/50308480-69f41280-04ac-11e9-9e07-dc35aeb73b0f.png">

**Versions:**
Version 3.1.3 (3.1.3.376)

**Comment by kraenhansen** [comment]
Hi @schurik77799 - thanks for reporting this.
Am I right in assuming that you've never downloaded Studio to this machine before?

**Comment by schurik77799** [comment]
Yes, you are right

**Comment by kraenhansen** [comment]
Version v3.2.0 of Studio will be releasing with a fix for this (+ some other enhancements) in the near future. Because this only happens on the very first boot of Studio I know it's hard for you to verify the fix - you would have to delete the `/Users/[username]/Library/Application Support/Realm Studio/` directory before starting the fixed version of Studio.

Thanks again for reporting this - sorry for any inconvenience this may have caused you or others.

**Comment by schurik77799** [comment]
Version 3.2.0 fixed an issue, thank you for the support.
