### ISSUE TITLE
Filtering or sorting creates incorrect reference

### ISSUE THREAD

**Issue by Tapestes** [realm/realm-studio#1085]
**Describe the bug**
Filtering or sorting a set class objects to be added as a property to another class results in the incorrect object being selected

**To Reproduce**
1. Create a realm file with two classes, let's say, Animal and Dog
2. Make three types of Dog
2. Set Dog class as a property in the Animal class
3. Select the Animal class in Realm Studio
4. In top right, select Create Animal
5. Under the Dog property, select Add Dog
6. Filter the Dog List so that only the last option shows
7. Select the last option
8. Result: instead of the last Dog in the list being added to the Dog property of Animal, the first Dog has been added

I suspect it's passing the index of the filtered table rather than the index of the Dog object in the full array of Dog objects

**Expected behavior**
In this example, the third Dog in the list should be added.

**Screenshots**
![bug](https://user-images.githubusercontent.com/6743048/51396532-3b9a3f00-1b0d-11e9-9fcc-cd134117f3c5.png)

**Versions:**
 - OS: Mac 10.14.2
 - Studio Version: 3.3

**Comment by kraenhansen** [comment]
Thanks for reporting this. I think you're indeed correct in your speculation that the object selected is from the unfiltered and unsorted result set.

For reference, this is where Studio selects the object(s) from the result: https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/Content/SelectObjectDialog/index.tsx#L111-L128 it uses indexes from the "highlight" but those refer to indexes in the sorted & filtered result, so they need to be "translated" into indexes in the original result set.

This issue is related but not the same https://github.com/realm/realm-studio/issues/831.
