### ISSUE TITLE
Display event log in UTC

### ISSUE THREAD

**Issue by VagueGit** [realm/realm-studio#1160]
Realm Studio currently displays log events in US date format. It would be easier, particularly for those of us not in the US, to match log events with user issues if the event log displayed UTC.

**Comment by rmsmani** [comment]
Being first time for the contribution, can you guide me where to start fixing this reqt...

**Comment by kraenhansen** [comment]
@rmsmani I believe this issue is in a part of the product which is no longer actively supported (the log view of the server administration view). As such, I'll actually go ahead and close this.

An alternative issue that is actively hurting users and has a limited scope might be https://github.com/realm/realm-studio/issues/1495.
