### ISSUE TITLE
no option to change a realm from full to reference

### ISSUE THREAD

**Issue by adrianchirita** [realm/realm-studio#1242]
**Describe the bug**
In Realm Studio 3.28.1 for Mac, no option to change a realm from full to reference

**To Reproduce**
1. Go to Realm Studio
2. Connect to Realm Cloud
3. Once connected, tap on Realms button near the Getting Started button
4. Tap on Create New Realm and create a new realm "newrealm". A new realm is created with the given name and of type "Full"
5. Select the newrealm in the realms table. A side menu is displayed and no option to upgrade/change your realm to reference.

**Expected behavior**
Once a realm is selected, the side menu should offer the option to change its type to Reference (from Full) as before.

**Screenshots**
screenshots added

**Versions:**
 - OS: MAC OS 10.15.2
 - Studio Version 3.8.3 
 - Realm Object Server version 3.28.1

**Additional context**
The realm instance is a Realm Cloud US instance
<img width="1187" alt="Screen Shot 2019-12-27 at 10 20 03 AM" src="https://user-images.githubusercontent.com/53476433/71509132-ed4ffd00-2892-11ea-933e-368a9b985301.png">
.

**Comment by adrianchirita** [comment]
The upgrade of realm from full to reference is possible with Realm Studio 3.7.0. I managed to overcome this issue by using an older version of Realm Studio (3.7.0), this defect is for v3.8.3. (possibly for v3.8.0+ as well) and needs to be addressed.

**Comment by kraenhansen** [comment]
The removal of the button to upgrade a full Realm to a reference Realm was deliberate (see #1226 ) as we're focussing on integrating full Realms for the upcoming integration with MongoDB. Please see the issue for our reasoning behind the change.

**Comment by adrianchirita** [comment]
Very disappointing (and costly) to see Realm veer off the type of statements like the one below: 
"..in general we are pushing everyone toward partial query-based sync. This is a more natural programming paradigm analogous to views in a SQL database or a REST request with a query parameter. **In the future this will be the default way to sync whereas the full realm way will be the older more legacy method**." https://forum.realm.io/t/single-realm-with-query-based-sync-vs-multiple-realm-performance/1361 

What is the guideline and impact for apps that are in production or close to production who based their realm approach on public product commitments like the one above and now are left in limbo by this move? I do not consider the ticket closed.

**Comment by nirinchev** [comment]
The Realm Studio repository is not the right place to ask roadmap/general guidance questions like these. Feel free to follow up on your concerns by opening a thread on the forum.

**Comment by adrianchirita** [comment]
According to the code of conduct of the repository, published here https://realm.io/conduct/ this is the right place to "accept constructive criticism", share "differing views and experiences" and "focus on what is best for the community". According to the GitHub Guidelines, published here https://guides.github.com "GitHub is great for managing all of the information _around_ the code." including documentation. There is no doubt that this change affects users which are part of the community and I have shared my experience around this change. I have asked above for additional technical documentation to support users that are in the same situation with us, as we have followed in the past various opinions expressed on the forum (see the forum post that I quoted) that brought us in the current uncertain situation. Official documentation should give us more confidence than an individual opinion on a forum post and it is normal to open issues on GitHub for documentation.

**Comment by nirinchev** [comment]
It's not about expressing criticism - you're free to do so as much as you want. It's just that you're asking for general advice on how to use realm, not facing a particular problem with studio. The removal of the upgrade button is a consequence of our decision to deprioritize query based sync so we can deliver a reliable and scalable solution for synchronizing with MongoDB. Regardless of whether we have that button or not, that decision remains and if you have concerns or questions about it, the forum is the right place to express those.

Regarding opinions here and on the forums - they are valid at the time they are posted. A year and a half ago, we were focusing on QBS as the primary way of interacting with Realm, but many things have happened since then. We still believe QBS is valuable and aim to eventually deliver a robust and scalable implementation, but we have higher priorities at the moment. You can consult [the roadmap](https://www.mongodb.com/realm#roadmap) for the current plan and again, if you have concerns or questions, feel free to share them in the forums or open a support ticket.
