### ISSUE TITLE
MongoDB Realm Studio 10 cannot open encrypted database 

### ISSUE THREAD

**Issue by aandea** [realm/realm-studio#1349]
**Describe the bug**
Using Java RealmDB 7.0.8, we have created an encrypted database (see attached file and key). Realm Studio 5.0.0 (and 5.0.1) can open the database just fine by providing the key. MongoDB Realm Studio gives an exception when trying to open the database

**To Reproduce**
Try to open the attached default.realm database

**Expected behavior**
Application asks for the key, then opens the database.

**Screenshots**
Application gives the following exception
Unable to open a realm at path '/Users/akin/Downloads/Database/default.realm': Realm file initial open failed Path:Exception backtrace:
0 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca39d1 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 49
1 .com.mongodb.realm-studio.VnC1oW 0x0000000110c664cd _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 3453
2 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca5caa _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3482
3 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca8d73 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243
4 .com.mongodb.realm-studio.VnC1oW 0x0000000110cad986 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 342
5 .com.mongodb.realm-studio.VnC1oW 0x0000000110753db5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277
6 .com.mongodb.realm-studio.VnC1oW 0x0000000110752d42 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62
7 .com.mongodb.realm-studio.VnC1oW 0x0000000110752ba8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 530
8 .com.mongodb.realm-studio.VnC1oW 0x000000011073cf8e _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128
9 .com.mongodb.realm-studio.VnC1oW 0x00000001106271ca _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234
10 .com.mongodb.realm-studio.VnC1oW 0x000000011062590e _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 334
11 .com.mongodb.realm-studio.VnC1oW 0x0000000110622289 _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135
12 .com.mongodb.realm-studio.VnC1oW 0x00000001106248da _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128
13 .com.mongodb.realm-studio.VnC1oW 0x00000001106247af _ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67
14 .com.mongodb.realm-studio.VnC1oW 0x0000000110624525 _ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ + 71
15 Electron Framework 0x000000010cfb57ca napi_create_function + 858
16 Electron Framework 0x00000001084622ec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844
17 Electron Framework 0x00000001084614b8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208
18 Electron Framework 0x0000000108460d9f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391
19 Electron Framework 0x0000000108e64999 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501289.

**Versions:**
 - OS: Tried on both Windows 10 and Mac OS 10.15.7
 - Studio Version: Only in MongoDB Realm 10.0.0. Works with Realm Studio 5.0.0
 - Realm Object Server version: N/A

**Additional context**
I have tried to upgrade the RealmDB in the application to version 10 (instead of 7.0.8) with similar results: MongoDB Realm Studio cannot open the encrypted database. It can open an un-encrypted version just fine.
[Database.zip](https://github.com/realm/realm-studio/files/5436167/Database.zip)

**Comment by kneth** [comment]
@aandea Thank you for reporting. I am able to open your Realm file with the following script:

```
const Realm = require("realm");


const hex = "<Your Encryption Key>;
var typedArray = new Uint8Array(hex.match(/[\da-f]{2}/gi).map(function (h) { return parseInt(h, 16) }));

const config = {
    encryptionKey: typedArray
};

let realm = new Realm(config);
console.log(`schema: ${JSON.stringify(realm.schema)}`);
```

After opening the file, it should be converted to file format v20 (JS v10.0.0). I see the same error message when opening the converted file using MongoDB Realm Studio.

To summarize, it is a bug and we need to dive a bit deeper to find a bug fix.

**Comment by johnsabilla** [comment]
I'm experiencing the same issue. I upgrade to io.realm:realm-gradle-plugin:10.0.0, download MongoDB Ream Studio 10.0.0. When i click on my database file (.realm) I get the error below instead of being prompted for a key.

Unable to open a realm at path '/Users/user/Desktop/tdrdb.realm': Realm file initial open failed Path:Exception backtrace: 0 .com.mongodb.realm-studio.ga3lPv 0x000000010ef779d1 ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9 + 49 1 .com.mongodb.realm-studio.ga3lPv 0x000000010ef3a4cd _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 3453 2 .com.mongodb.realm-studio.ga3lPv 0x000000010ef79caa _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3482 3 .com.mongodb.realm-studio.ga3lPv 0x000000010ef7cd73 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243 4 .com.mongodb.realm-studio.ga3lPv 0x000000010ef81986 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 342 5 .com.mongodb.realm-studio.ga3lPv 0x000000010ea27db5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277 6 .com.mongodb.realm-studio.ga3lPv 0x000000010ea26d42 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62 7 .com.mongodb.realm-studio.ga3lPv 0x000000010ea26ba8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 530 8 .com.mongodb.realm-studio.ga3lPv 0x000000010ea10f8e _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128 9 .com.mongodb.realm-studio.ga3lPv 0x000000010e8fb1ca _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234 10 .com.mongodb.realm-studio.ga3lPv 0x000000010e8f990e _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 334 11 .com.mongodb.realm-studio.ga3lPv 0x000000010e8f6289 _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135 12 .com.mongodb.realm-studio.ga3lPv 0x000000010e8f88da _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128 13 .com.mongodb.realm-studio.ga3lPv 0x000000010e8f87af ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67 14 .com.mongodb.realm-studio.ga3lPv 0x000000010e8f8525 ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info + 71 15 Electron Framework 0x00000001083097ca napi_create_function + 858 16 Electron Framework 0x00000001037b62ec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844 17 Electron Framework 0x00000001037b54b8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208 18 Electron Framework 0x00000001037b4d9f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391 19 Electron Framework 0x00000001041b8999 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501289.

**Note**:
If I revert back to io.realm:realm-gradle-plugin:7.0.8 and use Realm Studio 5.0, create a db and encrypt it, I am able to decrypt db file (so it's not our code).

**Version**:
- OS: MacOS 10.15.7
- Studio Version: MongoDB Realm Studio 10.0.0.  Android Studio 4.1
- Library: io.realm:realm-gradle-plugin:10.0.0

**Comment by jaspal27** [comment]
I am having the same issue with Mongo RealmDB Studio 10 and encrypted databases.
i am getting below issue while  open a realm at path '/Users/uname/tdrdb.realm': Realm file initial open failed Path:Exception backtrace: 0 .com.mongodb.realm-studio.ga3lPv 0x000000010ef779d1
0 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca39d1 ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9 + 49
1 .com.mongodb.realm-studio.VnC1oW 0x0000000110c664cd _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 3453
2 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca5caa _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3482
3 .com.mongodb.realm-studio.VnC1oW 0x0000000110ca8d73 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243
4 .com.mongodb.realm-studio.VnC1oW 0x0000000110cad986 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 342
5 .com.mongodb.realm-studio.VnC1oW 0x0000000110753db5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277
6 .com.mongodb.realm-studio.VnC1oW 0x0000000110752d42 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62
7 .com.mongodb.realm-studio.VnC1oW 0x0000000110752ba8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 530
8 .com.mongodb.realm-studio.VnC1oW 0x000000011073cf8e _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128
9 .com.mongodb.realm-studio.VnC1oW 0x00000001106271ca _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234
10 .com.mongodb.realm-studio.VnC1oW 0x000000011062590e _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 334
11 .com.mongodb.realm-studio.VnC1oW 0x0000000110622289 _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135
12 .com.mongodb.realm-studio.VnC1oW 0x00000001106248da _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128
13 .com.mongodb.realm-studio.VnC1oW 0x00000001106247af ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67
14 .com.mongodb.realm-studio.VnC1oW 0x0000000110624525 ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info + 71
15 Electron Framework 0x000000010cfb57ca napi_create_function + 858
16 Electron Framework 0x00000001084622ec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844
17 Electron Framework 0x00000001084614b8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208
18 Electron Framework 0x0000000108460d9f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391
19 Electron Framework 0x0000000108e64999 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501289.

OS: MacOS 10.15.7
Studio Version: MongoDB Realm Studio 10.0.0. Android Studio 4.1
Library: io.realm:realm-gradle-plugin:10.0.0

**Comment by softmastx** [comment]
Same here!

OS: MacOS 10.15.7
Studio Version: MongoDB Realm Studio 10.0.0. Xcode 12.1 
Framework: Objc-10.1.2

```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
NSData *keyData = [key dataUsingEncoding:NSASCIIStringEncoding];
RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];
```

<img width="1266" alt="Screen Shot 2563-11-11 at 21 06 53" src="https://user-images.githubusercontent.com/1833053/98823179-5a955e00-2464-11eb-9bcc-0c784e60ac1c.png">
