### ISSUE TITLE
“Realm Studio” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by teslum** [realm/realm-studio#1350]
I downloaded Realm Studio on my iMac running Catalina (10.15.6) using the link in the App Store for the deprecated "Realm Browser": [https://docs.realm.io/sync/realm-studio](url). Attempting to run the installed Realm Studio app on the Mac pops up an error:

![image](https://user-images.githubusercontent.com/73007292/97531296-91776880-19bc-11eb-9bfd-5a551bd09450.png)

It says "Contact the developer for more information".

**Comment by kneth** [comment]
@teslum Thank you for "contacting the developer" :smile:

Do you allow "apps downloaded from anywhere" or only "apps downloaded from App Store"?

**Comment by kraenhansen** [comment]
@teslum please go to https://docs.realm.io/sync/realm-studio and try downloading it again.
We had an issue where you would accidentally get an older version (which is not being notarized) instead of the latest (v10.0.0) version of MongoDB Realm Studio.
Please reopen if the issue persists after downloading MongoDB Realm Studio v10.0.0.

**Comment by steffenagger** [comment]
Seems like this is in regards to an older version (Realm Studio).
The reason is that only the latest version has been notarized by apple. A quick way to get older version working (without UI), is running: `xattr -rd com.apple.quarantine /Applications/Realm\ Studio.app`

(The command above removes the `com.apple.quarantine` attribute from the app, this is the attribute that triggers Apple's Gatekeeper)

**Comment by teslum** [comment]
OK, it looks like downloading from the link again resulted in installation
of "MondoDB Realm Studio" which appears to work. I can see the test
database that I am setting up within it. But as a newbie in all this, I
must admit that the terminology gets really confusing:

Realm
Realm Browser
Realm Studio
MondoDB Realm Studio
etc.....

Honestly, at this point, I am not sure what's the difference between Realm
Studio and MondoDB Realm Studio. But I'll settle with using it for the
moment and move on.

-Tim

**Comment by kraenhansen** [comment]
> Honestly, at this point, I am not sure what's the difference between Realm Studio and MondoDB Realm Studio. But I'll settle with using it for the moment and move on.

Following up, since I didn't provide an answer to your last statement.

Realm Studio (v5 and below) can be used to access the legacy Realm Object Server (and [legacy Realm Cloud](https://cloud.realm.io/)). It's also able to open Realm database files produced by SDKs up until (but not including) v10 of the SDKs.

If you need to open Realm files that are produced by SDKs from v10 or higher, you need to use MongoDB Realm Studio, which is basically the v10 of Realm Studio, but with a different name ("MongoDB" prefixed) to support running both this and an older Realm Studio, side-by-side.

The Realm Browser was our data browser for MacOS, but that's been deprecated for a couple of years now and will not receive updates as the SDKs and file formats progress. You shouldn't need to worry about installing that.

I hope this brings some clarity.
