### ISSUE TITLE
cannot open realm studio

### ISSUE THREAD

**Issue by jinsu3758** [realm/realm-studio#1375]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24262765/102756633-8a187e00-43b3-11eb-8a01-d030fc4c367b.png)

When I open realm studio, the following warning message appears. If you press 'Backup and upgrade' or that 'Upgrade in-place' over there, the realm doesn't work in the app.

**Versions:**
 - OS: Mac 10.15.7
 - Studio Version 10.0.1

**Comment by derrikF** [comment]
The database is sure to open in the version 3.10.1 https://github.com/realm/realm-studio/releases/tag/v3.10.1

**Comment by kneth** [comment]
Version 10.0.0  of Realm Studio and all SDKs will be using a different file format. Upgrading to this new file format means that older SDK versions cannot open the Realm files. I believe this is what you are experiencing. If you don't plan to upgrade your app to a recent Realm SDK version, you should use Realm Studio v4.0.0 or older (see also "Breaking changes" section in https://github.com/realm/realm-studio/blob/channel/major-10/CHANGELOG.md#release-400-2020-09-22).

**Comment by kraenhansen** [comment]
As @kneth mentioned above, the upgrade of file format makes the Realm unable to be loaded from the app if it's using an SDK with an outdated file format version.

I've created an issue to track an enhancement to add a button that would make a copy and upgrade the new file instead of the original. See https://github.com/realm/realm-studio/issues/1286. Would this help your workflow?

As such, I'm closing this issue, since I believe Realm Studio is behaving as expected.
