### ISSUE TITLE
Add ability to go back/up to parent when viewing embedded objects

### ISSUE THREAD

**Issue by AdamGerthel** [realm/realm-studio#1495]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm traversing a stored objects that have a lot of embedded objects, because I can't go "back" or "up" one step. So whenever I've clicked on an embedded object to open it, and I want to go back to its parent object, the only way seems to be to use the panel on the left to start all over from scratch again.

**Describe the solution you'd like**
To be able to go back/up one step using a button - somewhere close to the query input or wherever at the top of the UI. Ability to go forward could be useful too, similar to when using a browser.

**Describe alternatives you've considered**
Using hotkeys.

**Comment by tomduncalf** [comment]
Thanks for the suggestion @AdamGerthel, we'll discuss this and update you if we decide to implement it

**Comment by BlueCobold** [comment]
Any news on this? That feature would be so welcome in general.

**Comment by mr-mmmmore** [comment]
Would be great to implement this, without it some use cases are really painful, for example:

- Run a query in one of the "tables"
- Go recursively inside embedded objects of one of the results (parent > embedded child > embedded grand-child…)
- When you're there, you can't go back one or n levels up, all you can do is go back to the default view of the parent "table". The query is lost.

The fact that there was a query makes it more painful but the same applies without a query: it is simply a pain to navigate inside an object's tree since we can only go downward.

**Comment by BlueCobold** [comment]
I don't think the issue was solved. At least not based on the description of the PR. Navigation to top wasn't the only purpose, but to keep the search-terms in tact when navigating back.
