### ISSUE TITLE
JSON export is destroyed in v. 14.0.3

### ISSUE THREAD

**Issue by robertnicjoo** [realm/realm-studio#1582]
**Describe the bug**
After updating to version 14.0.3 when I export my data as JSON it exports as numbers and texts at the bottom of file in separate objects. Nothing is in their places like it used to be.

**To Reproduce**
1. Go to 'File'
2. Click on 'Save Data -> JSON'
3. See generated file.

**Expected behavior**
Each array and its objects be in their place and not replaced by random numbers.

**Screenshots**
![1](https://github.com/realm/realm-studio/assets/8672823/f15df3d7-1d1f-43ff-ae5e-d0a949ce815c)
![2](https://github.com/realm/realm-studio/assets/8672823/8fb02d8e-4c23-401b-9d39-8b580a2c0023)
![3](https://github.com/realm/realm-studio/assets/8672823/f51ed4b3-e297-482a-9ccb-004db9538f6c)

**Versions:**
 - OS: Mac
 - Studio Version 14.0.3

**Additional context**

Please advise on how to fix this extremely important issue.

**Comment by kneth** [comment]
@robertnicjoo Is it correct to assume that the file was created with an older version of a Realm SDK, and Studio has upgraded the file format for you?

We would like to reproduce the issue locally, and is it possible for you to email us the Realm file? You can send it to `realm-help@mongodb.com`.

**Comment by robertnicjoo** [comment]
> @robertnicjoo Is it correct to assume that the file was created with an older version of a Realm SDK, and Studio has upgraded the file format for you?
> 
> 
> 
> We would like to reproduce the issue locally, and is it possible for you to email us the Realm file? You can send it to `realm-help@mongodb.com`.

Hi @kneth ,
Yes it's been upgraded by studio latest version.

[Here is last working realm file](https://github.com/robertnicjoo/alkitab.github.io/blob/21d1e2a2c842d0adb58f20d9364c7215842f714e/assets/assets/db/id.realm) on GitHub. Simply update any field by studio latest version and you'll get broken results like mine.

**Comment by robertnicjoo** [comment]
@kneth any update on this?

**Comment by kneth** [comment]
In order to investigate it, I have created a small node.js script to export your Realm file to JSON in a similar way as Studio is doing.

The `package.json` is:

```json
{
  "name": "studio-1582",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "flatted": "^3.2.7",
    "realm": "11.5.0"
  }
}
```

And the script `export.js` is:

```js
const Realm = require("realm");
const { stringify } = require('flatted');
let realm = new Realm({ path: "id.realm" });
realm.schema.forEach(s => console.log(stringify(realm.objects(s.name).toJSON())));
realm.close();
```

I have exporting using Realm JavaScript v11.5.0 and v11.9.0, and `diff` doesn't report any differences.

Please understand that Realm doesn't guarantee the order, and you might want to model differently by using [relationships](https://www.mongodb.com/docs/realm/sdk/node/model-data/relationships-and-embedded-objects/).

**Comment by robertnicjoo** [comment]
@kneth version 11 is not the problem, the realm file even was created by 11.2.0 problem caused on version 14 (latest version).

Anyway: it would be great if you simply load the file in studio instead of making node scripts so you can exactly experience what I have. That might help with finding where issue is caused from.

PS:
As I mentioned this file that you have right now is working file. If you edit it on studio 14 then you see json results are broken.

### Update

**[This is](https://github.com/robertnicjoo/alkitab.github.io/blob/21d1e2a2c842d0adb58f20d9364c7215842f714e/assets/assets/db/id.json)** what results should be look like if everything work as it supposed to.

> This result is made by **linked realm above** and **realm studio 11.2.0**


### Update 2

@kneth here is working script by nodejs but need your help to implement it in studio app so we don't have to write node script each time updating realm file.


```javascript
const Realm = require("realm");
const { stringify } = require('flatted');
const fsPromises = require('fs').promises; 

let realm = new Realm({ path: "id.realm" });

const data = {};
realm.schema.forEach(
    s => data[s.name] = realm.objects(s.name).toJSON()
);
fsPromises.writeFile('myFile.json', JSON.stringify(data))
        .then( () => { console.log('JSON saved'); })
        .catch(er => { console.log(er);});

realm.close();
```

**Comment by kneth** [comment]
@robertnicjoo Please notice that we in [Studio v13.0.0](https://github.com/realm/realm-studio/releases/tag/v13.0.0) changed how we export JSON. 

The reason for the change is that we wanted to be able to support circular object graphs. In order to use the exported JSON in another app, you will have to use [flatted](https://www.npmjs.com/package/flatted). The script below will produce the same output as [your file](https://github.com/robertnicjoo/alkitab.github.io/blob/21d1e2a2c842d0adb58f20d9364c7215842f714e/assets/assets/db/id.json).

```js
const { parse, stringify } = require('flatted');
const fsPromises = require('fs').promises; 

let data = {};
fsPromises.readFile('myFile.json')
        .then( (data) => { console.log(parse(data)); })
        .catch(er => { console.log(er);});

```

Yes, Realm Studio v14 will produce a different JSON file because we want to support a broader set of object graphs.
