### ISSUE TITLE
Dictionary type --> JSON Viewer

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-studio#1583]
**Describe the bug**
I can't see dictionary type correctly in realm studio. 

**To Reproduce**
click dictionay column/s

**Expected behavior**
I want to see my dictionary column like this {city:'MARDİN'}

**Screenshots**

**Versions:**
 - OS: MAC
 - Studio Version: 14.0.3

<img width="497" alt="Screen Shot 2023-05-31 at 17 41 12" src="https://github.com/realm/realm-studio/assets/44754934/273c6e8a-b5da-42d8-8b5c-abe04e4d562a">

**Comment by kneth** [comment]
You are right, the output isn't so readable. In Realm JavaScript v11.0.0 we switch our `toJSON()` methods to output a format compatible with [flatted](https://github.com/WebReflection/flatted) in order to support circular object graphs. Studio is currently simply stringifying which produce this result.

**Comment by MuratAkbaba006** [comment]
Thank you for clarification.
