### ISSUE TITLE
How to get notifications when Realm Studio has incident or releases new version?

### ISSUE THREAD

**Issue by dduong166** [realm/realm-studio#1599]
I want to receive notifications when Realm Studio releases a new version, or notifications about updates, security errors,...
How can I subscribe to such notifications?

**Comment by kraenhansen** [comment]
As we publish releases here on GitHub a solution that might work for you is simply to watch this repository.

I'm curious why you see a need for this, since Realm Studio automatically upgrades as new releases are published. (Admittedly not across major versions to avoid interruptions in the workflow of developers).
