### ISSUE TITLE
Realm Studio shows wrong Int value than the value stored in RealmSwift

### ISSUE THREAD

**Issue by guhan0** [realm/realm-studio#861]
**Describe the bug**
Realm Studio shows wrong Int value than the value stored in RealmSwift

**To Reproduce**
1. Go to Xcode save a Int in RealmSwift 
2. Open Realm Studio and see that wrongly showing number value 
3. But again fetching the results in Xcode via RealmSwift gives back correct Int number.

**Expected behavior**
It should display correct number in Realm Studio

**Screenshots**
I have attached the screen recording of this issue clearly.
[Screen Recording (1).mov.zip](https://github.com/realm/realm-studio/files/2135891/Screen.Recording.1.mov.zip)

**Versions:**
 - OS: MacOS High Sierra 
 - Xcode: 9.4.1
 - Studio Version: 2.3.1
 - RealmSwift: 3.7.2

**Comment by kraenhansen** [comment]
This happens because JavaScript (the language that Realm Studio is transpiled to) does not have the concept of integers. All integers read from the Realm is actually represented as a floating point `number` internally.

The number you are writing to the realm (126483000004003060) is rather large. The largest integer that Studio (or any other JavaScript application) can safely read is around a hundred times smaller (9007199254740991 ... see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

As this is an ID I suspect that you are not performing arithmetic operations on the number and I would suggest that you store this as a string instead.

For now we cannot really do anything about this limitation of JavaScript. We've debated possibly enabling Realm JS to open Realms and representing integers as [BigInt](https://developers.google.com/web/updates/2018/05/bigint) but unfortunately that API is not available in Node.js which Realm JS also has to support.

I hope this helps clarify why you're seeing what you're seeing, but I'll close the issue for now.

Thanks for reaching out!

**Comment by guhan0** [comment]
Thanks for the clear explanation and as you said this is "ID" & not performing arithmetic operations on the number and I am storing this as a string instead. @kraenhansen 🙏🏻🙏🏻
