### ISSUE TITLE
Can import from CSV file object. What is correct format?

### ISSUE THREAD

**Issue by worm69** [realm/realm-studio#875]
I cant import from CSV file any field that use Objects.
I am not sure what format should use to can import objects types but can link them creating a new one.
<img width="958" alt="import object csv" src="https://user-images.githubusercontent.com/12191069/42885395-b8d02166-8a98-11e8-9772-ed56e24d42ce.PNG">

**Versions:**
 - OS: Windows
 - Studio Version 2.4.1

Can provide csv file and realm db to.

**Comment by kraenhansen** [comment]
I agree this would be very useful, but unfortunately we havn't added this just yet, hence this issue is a duplicate of https://github.com/realm/realm-studio/issues/816 ... Thanks for letting us know that this would be valuable to you. Please subscribe to the other issue to know when it gets fixed and released.
