### ISSUE TITLE
Importing data from CSV behaves randomly

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-studio#954]
When connected to a server and choosing File/Create Realm From/CSV I have seen 4 outcomes:

1. The data is imported like I expect
2. I am asked where to store the imported data, and the data will be put into a local realm.
3. An error window comes up saying "Failed when importing data: Bad server version (IDENT, UPLOAD)". The realm is created, but is completely empty.
4. I could choose what to import, but when I should type the path on the server, the buttons were inactive so I could neither press "Create Realm" nor "Cancel".

If I end up in situation 4 I have to reconnect to the server before being able to import again.

**Versions:**
 - OS: Linux
 - Studio Version 2.8.0
 - Realm Object Server version 3.11.0

**Comment by kraenhansen** [comment]
I can reproduce outcome 3 (the "Bad server version (IDENT, UPLOAD))" error) if I import into a path, delete the Realm from the server and import to the same path again. This is probably because Studio does not remove its local copy of the realm and does not handle client resets correctly.

I cannot reproduce outcome 4. @jedelbo can I have you try that again? I did make some changes to the UI since end of September.

There are two different behaviours when clicking "Create Realm from":
1. In the Server Administration window you create the Realm on the server before importing.
2. From any other window, you create a local file.

We should probably make a separate menu item to "Create Realm on Server from" instead of overloading the "Create Realm from" (importing to a local file - which we could rename to "Create local Realm from").

**Comment by roberhofer** [comment]
@kraenhansen : I am good with offering more options for "create realm from". 
On the "studio does not remove its local copy of the realm": Any ideas how to improve this? 
It seems clear that we do have plenty people who (in the development phase) frequently iterate on Realms.

**Comment by kraenhansen** [comment]
This could be considered a regression introduced by allowing Realm JS to cache the Realms https://github.com/realm/realm-studio/pull/970 .. I believe we can use [`Realm.deleteFile`](https://realm.io/docs/javascript/latest/api/Realm.html#.deleteFile) to delete the local file (if any) when deleting it from the server. We should also ensure any Realm browser windows with the file opened gets closed when deleting the Realm from the server (solving https://github.com/realm/realm-studio/issues/882).

**Comment by kraenhansen** [comment]
I think the root cause of #1065 is the same as for this issue (see https://github.com/realm/realm-studio/issues/1065#issuecomment-451978815). I think the fix for the first can be applied for the browser window as well as the server administration window.
